<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>
<div class="page-header" style="margin-top: 50px">
    <h1>
        Добавление праздника
    </h1>
</div>

<?php

echo $this->flash->output();

echo $this->tag->form(
    [
        "holidays/create",
        "autocomplete" => "off",
    ]
);
?>

<hr>

<div class="form-group row">
    <label for="fieldDate" class="col-sm-2 col-form-label">Дата</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate", "placeholder" => "Формат: 2018-12-21"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldName" class="col-sm-2 col-form-label">Название</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Добавить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
