<div class="page-header" style="margin-top: 150px; text-align: center">
    <h1>Вход в систему</h1>
</div>

<hr>
<?php

echo $this->flash->output();

echo $this->tag->form(
    array(
        "auth/login",
        "autocomplete" => "off",
    )
);
?>

<div class="form-group row">
    <label for="inputId" class="col-sm-2 col-form-label">Табельный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->numericField(array("id_user", "class" => "form-control", "id" => "inputId", "required" => "", "placeholder" => "Введите табельный номер")) ?>
    </div>
</div>
<div class="form-group row">
    <label for="inputPassword" class="col-sm-2 col-form-label">Пароль</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(array("password", "class" => "form-control", "id" => "inputPassword", "required" => "", "placeholder" => "Введите пароль")) ?>
    </div>
</div>

<div class="form-group row">
    <label for="inputRole" class="col-sm-2 col-form-label">Роль</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "role",
                Roles::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "inputRole"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="" class="col-sm-2 col-form-label"></label>
    <div class="col-sm-10">
        <?php echo $this->tag->submitButton(array("Вход", "class" => "btn btn-primary")) ?>
    </div>
</div>


<?php echo $this->tag->endForm(); ?>

