

<div class="page-header" style="margin-top: 50px; text-align: center">
    <h1>Добро пожаловать, <?php echo $user_fio; ?></h1>
</div>
<?php echo $this->flash->output(); ?>
<hr>
<?php if (isset($user_role_1)): ?>

    <?php echo $this->tag->linkTo(array('/users/new', 'Добавить новую карточку', 'class' => 'btn btn-success', 'role' => 'button')); ?>
    <?php echo $this->tag->linkTo(array('/users/index', 'Поиск', 'class' => 'btn btn-primary', 'role' => 'button')); ?>
    <hr>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">№ п/п</th>
            <th scope="col">Табельный номер</th>
            <th scope="col">ФИО</th>
            <th scope="col">Роли</th>
            <th scope="col">Пароль</th>
            <th scope="col">Просмотр</th>
            <th scope="col">Редактировать</th>
        </tr>
        </thead>
        <tbody>

        <?php

        $i = 0;
        foreach ($all_users as $user) {
            echo "<tr>";
            $i++;
            echo "<th scope=\"row\">$i</th>";
            echo "<th >$user->t_number</th>";
            echo "<td>$user->fio</td>";

            echo "<td>";
            $Roles = $user->getUserRoles();
            foreach ($Roles as $role) {
                echo $role->getRoles()->name . "; ";

            }
            echo "</td>";
            echo "<td>***</td>";
            echo "<td>" . $this->tag->linkTo(array('/users/show/' . $user->id, 'Просмотр', 'class' => 'btn btn-success', 'role' => 'button')) . "</td>";
            echo "<td>" . $this->tag->linkTo(array('/users/edit/' . $user->id, 'Редактировать', 'class' => 'btn btn-warning', 'role' => 'button')) . "</td>";
            echo "</tr>";
        }

        ?>

        </tbody>
    </table>
<?php endif;


