<div class="page-header" style="margin-top: 50px; text-align: center">
    <h1>Добро пожаловать, <?php echo $user_fio; ?></h1>
</div>
<hr>
<?php if ($user_role_1): ?>

    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">№ п/п</th>
            <th scope="col">Табельный номер</th>
            <th scope="col">ФИО</th>
            <th scope="col">Роли</th>
            <th scope="col">Пароль</th>
        </tr>
        </thead>
        <tbody>

        <?php

        $i=0;
        foreach ($all_users as $user) {
            echo "<tr>";
            $i++;
                echo "<th scope=\"row\">$i</th>";
                echo "<th >$user->id</th>";
                echo "<td>$user->fio</td>";

                echo "<td>";
                $Roles = $user->getUserRoles();
                foreach ($Roles as $role){
                    echo $role->getRoles()->name."; ";

                }
                echo "</td>";
                echo "<td>***</td>";
            echo "</tr>";
        }

        ?>

        </tbody>
    </table>
<?php endif;