<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header" style="margin-top: 50px">
    <h1>
        Поиск карточки
    </h1>
</div>

<?php

echo $this->flash->output();


echo $this->tag->form(
    [
        "users/search",
        "autocomplete" => "off",
    ]
);
?>

<hr>

<div class="form-group row">
    <label for="fieldFio" class="col-sm-2 col-form-label">Табельный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["t_number", "size" => 30, "class" => "form-control", "id" => "fieldFio"]) ?>
    </div>
</div>


<div class="form-group row">
    <label for="fieldFio" class="col-sm-2 col-form-label">ФИО</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fio", "size" => 30, "class" => "form-control", "id" => "fieldFio"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldIdentityCode" class="col-sm-2 col-form-label">Идентификационный код</label>
    <div class="col-sm-10">
        <?php echo $this->tag->numericField(["identity_code", "type" => "number", "class" => "form-control", "id" => "fieldIdentityCode"]) ?>
    </div>
</div>


<div class="form-group row">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Поиск", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
