<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>


<div class="page-header" style="margin-top: 50px">
    <h1>
        Добавление карточки
    </h1>
</div>

<?php

echo $this->flash->output();


echo $this->tag->form(
    array(
        "users/create",
        "autocomplete" => "off",
    )
);
?>

<hr>

<div class="form-group row">
    <label for="fieldFio" class="col-sm-2 col-form-label">Табельный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["t_number", "size" => 30, "class" => "form-control", "id" => "fieldFio"]) ?>
    </div>
</div>


<div class="form-group row">
    <label for="fieldFio" class="col-sm-2 col-form-label">ФИО</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fio", "size" => 30, "class" => "form-control", "id" => "fieldFio"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldPass" class="col-sm-2 col-form-label">Пароль</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(["pass", "size" => 30, "class" => "form-control", "id" => "fieldPass"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldRegNumber" class="col-sm-2 col-form-label">Регистрационный номер</label>
    <div class="col-sm-10">
        <?php echo $this->tag->numericField(["reg_number", "type" => "number", "class" => "form-control", "id" => "fieldRegNumber"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldIdentityCode" class="col-sm-2 col-form-label">Идентификационный код</label>
    <div class="col-sm-10">
        <?php echo $this->tag->numericField(["identity_code", "type" => "number", "class" => "form-control", "id" => "fieldIdentityCode"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldGender" class="col-sm-2 col-form-label">Пол</label>
    <div class="col-sm-10">

        <?php //echo $this->tag->textField(["gender", "size" => 30, "class" => "form-control", "id" => "fieldGender"]) ?>
        <?php echo $this->tag->select(
            array(
                "gender",
                ["Мужской" => "Мужской", "Женский" => "Женский"],
                "required" => "",
                "class" => "form-control",
                "id" => "fieldGender"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldBirthDate" class="col-sm-2 col-form-label">Дата рождения</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["birth_date", "type" => "date", "class" => "form-control", "id" => "fieldBirthDate", "placeholder" => "Формат: 2018-12-21"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldDateRec" class="col-sm-2 col-form-label">Дата приема</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date_rec", "type" => "date", "class" => "form-control", "id" => "fieldDateRec", "placeholder" => "Формат: 2018-12-21"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldOidRec" class="col-sm-2 col-form-label">Приказ на прием</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "oid_rec",
                Orders::find(),
                "using" => array("id", "number"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldOidRec"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldPid" class="col-sm-2 col-form-label">Профессия</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "pid",
                Professions::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldPid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldAid" class="col-sm-2 col-form-label">Участок</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "aid",
                Areas::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldAid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldCid" class="col-sm-2 col-form-label">Разряд</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "cid",
                Categories::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldCid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group  row">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Сохранить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
