<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>


<div class="page-header" style="margin-top: 50px">
    <h1>
        Результаты поиска карточки
    </h1>
</div>

<?php

echo $this->flash->output();

?>

<div class="row">
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">№ п/п</th>
            <th scope="col">Табельный номер</th>
            <th scope="col">ФИО</th>
            <th scope="col">Роли</th>
            <th scope="col">Пароль</th>
            <th scope="col">Редактировать</th>

        </tr>
        </thead>
        <tbody>

        <?php

        $i = 0;
        foreach ($page->items as $user) {
            echo "<tr>";
            $i++;
            echo "<th scope=\"row\">$i</th>";
            echo "<th >$user->t_number</th>";
            echo "<td>$user->fio</td>";

            echo "<td>";
            $Roles = $user->getUserRoles();
            foreach ($Roles as $role) {
                echo $role->getRoles()->name . "; ";

            }
            echo "</td>";
            echo "<td>***</td>";
            echo "<td>" . $this->tag->linkTo(array('/users/edit/' . $user->id, 'Редактировать', 'class' => 'btn btn-success', 'role' => 'button')) . "</td>";
            echo "</tr>";
        }

        ?>
        </tbody>
    </table>
</div>
