<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header" style="margin-top: 50px">
    <h1>
        Редактирование приказа
    </h1>
</div>

<?php

echo $this->flash->output();


echo $this->tag->form(
    array(
        "orders/save",
        "autocomplete" => "off",
    )
);
?>

<hr>

<div class="form-group row">
    <label for="fieldDate" class="col-sm-2 col-form-label">Дата</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "size" => 30, "class" => "form-control", "id" => "fieldDate"]) ?>
    </div>
</div>


<div class="form-group row">
    <label for="fieldNumber" class="col-sm-2 col-form-label">№ приказа</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["number", "size" => 30, "class" => "form-control", "id" => "fieldNumber"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldNote" class="col-sm-2 col-form-label">Примечания</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["note", "size" => 30, "class" => "form-control", "id" => "fieldNote"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Сохранить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
