<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header" style="margin-top: 50px">
    <h1>
        Результаты поиска приказов
    </h1>

    <p><?php echo $this->tag->linkTo(["orders/new", "Создать"]); ?></p>
</div>

<?php echo $this->flash->output(); ?>

<div class="row">
    <table class="table table-hover">
        <thead>
        <tr>
            <th>Id</th>
            <th>Дата</th>
            <th>№ приказа</th>
            <th>Примечания</th>

            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $order): ?>
            <tr>
                <td><?php echo $order->id ?></td>
                <td><?php echo $order->date ?></td>
                <td><?php echo $order->number ?></td>
                <td><?php echo $order->note ?></td>

                <td><?php echo $this->tag->linkTo(["orders/edit/" . $order->id, 'class' => 'btn btn-warning', "Редактировать"]); ?>
                    <?php echo $this->tag->linkTo(["orders/delete/" . $order->id, 'class' => 'btn btn-danger', "Удалить"]); ?></
                >
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
