<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header" style="margin-top: 50px">
    <h1>
        Редактирование перевода
    </h1>
</div>

<?php

echo $this->flash->output();


echo $this->tag->form(
    array(
        "transfers/save",
        "autocomplete" => "off",
    )
);
?>

<hr>

<div class="form-group row">
    <label for="fieldUid" class="col-sm-2 col-form-label">Регистрационный номер работника</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "uid",
                Users::find(),
                "using" => array("id", "reg_number"),
                "class" => "form-control",
                "id" => "fieldUid",
                'useEmpty' => true,
                'emptyText' => 'Выберите работника',
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldDate" class="col-sm-2 col-form-label">Дата</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["date", "type" => "date", "class" => "form-control", "id" => "fieldDate", "placeholder" => "Формат: 2018-12-21"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldAid" class="col-sm-2 col-form-label">Участок</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "aid",
                Areas::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldAid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldPid" class="col-sm-2 col-form-label">Профессия</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "pid",
                Professions::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldPid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldCid" class="col-sm-2 col-form-label">Разряд</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "cid",
                Categories::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldCid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldSalary" class="col-sm-2 col-form-label">Оклад</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["salary", "size" => 30, "class" => "form-control", "id" => "fieldSalary"]) ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldOid" class="col-sm-2 col-form-label">Приказ</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "oid",
                Orders::find(),
                "using" => array("id", "number"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldOid"
            )
        );
        ?>
    </div>
</div>

<div class="form-group row">
    <label for="fieldCause" class="col-sm-2 col-form-label">Причина перевода</label>
    <div class="col-sm-10">
        <?php echo $this->tag->select(
            array(
                "cause",
                TransferCause::find(),
                "using" => array("id", "name"),
                "required" => "",
                "class" => "form-control",
                "id" => "fieldCause"
            )
        );
        ?>
    </div>
</div>

<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group  row">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Сохранить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
