<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>
<div class="page-header" style="margin-top: 50px">
    <h1>
        Результаты поиска
    </h1>
</div>

<?php

echo $this->flash->output();

?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Регистрационный номер</th>
            <th>Дата</th>
            <th>Участок</th>
            <th>Профессия</th>
            <th>Разряд</th>
            <th>Оклад</th>
            <th>№ приказа</th>
            <th>Причина</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $transfer): ?>
            <tr>
            <td><?php echo $transfer->getUsers()->reg_number ?></td>
            <td><?php echo $transfer->date ?></td>
            <td><?php echo $transfer->getAreas()->name ?></td>
            <td><?php echo $transfer->getProfessions()->name ?></td>
            <td><?php echo $transfer->getCategories()->name ?></td>
            <td><?php echo $transfer->salary ?></td>
            <td><?php echo $transfer->getOrders()->number ?></td>
            <td><?php echo $transfer->getTransferCause()->name ?></td>

                <td><?php echo $this->tag->linkTo(["transfers/edit/" . $transfer->id, 'class' => 'btn btn-success', "Редактировать"]); ?></td>
                <td><?php echo $this->tag->linkTo(["transfers/delete/" . $transfer->id, 'class' => 'btn btn-success', "Удалить"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
