<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="page-header" style="margin-top: 50px">
    <h1>
        Результаты поиска
    </h1>
</div>

<?php

echo $this->flash->output();

?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
            <th>Регистрационный номер</th>
            <th>Тип отпуска</th>
            <th>Кол-во дней</th>
            <th>Дата начала</th>
            <th>Дата окончания</th>
            <th>№ приказа</th>
            <th>Примечания</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $vacation): ?>
            <tr>
            <td><?php echo $vacation->getUsers()->reg_number ?></td>
            <td><?php echo $vacation->type ?></td>
            <td><?php echo $vacation->count_day ?></td>
            <td><?php echo $vacation->date_start ?></td>
            <td><?php echo $vacation->date_end ?></td>
            <td><?php echo $vacation->getOrders()->number ?></td>
            <td><?php echo $vacation->note ?></td>

                <td><?php echo $this->tag->linkTo(["vacation/edit/" . $vacation->id, 'class' => 'btn btn-success', "Редактировать"]); ?></td>
                <td><?php echo $this->tag->linkTo(["vacation/delete/" . $vacation->id, 'class' => 'btn btn-success', "Удалить"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

