<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Phalcon PHP Framework</title>
    <link rel="stylesheet" href="<?php echo $this->url->get('css/bootstrap.min.css'); ?>">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico'); ?>"/>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">Security App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <?php if ($this->session->has("id_user") and $this->session->get("id_role") == 1): ?>
                <a class="nav-item nav-link" href="/index/workroom">Карточки</a>
                <a class="nav-item nav-link" href="#">Отпуска</a>
                <a class="nav-item nav-link" href="/orders">Приказы</a>
                <a class="nav-item nav-link" href="#">Формы</a>
                <a class="nav-item nav-link" href="#">Документы</a>
                <a class="nav-item nav-link" href="#">Списки</a>
                <a class="nav-item nav-link" href="#">Сервис</a>
            <?php endif; ?>
        </div>
    </div>

    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <?php if ($this->session->has("id_user")): ?>
                    <a class="nav-link" href="/auth/exit">Выход</a>
                <?php else: ?>
                    <a class="nav-item nav-link" href="/">Вход</a>
                <?php endif; ?>
            </li>
        </ul>
    </div>
</nav>


<div class="container">
    <?php echo $this->getContent(); ?>
</div>
<!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
<script src="<?php echo $this->url->get('js/jquery-3.2.1.slim.min.js'); ?>"></script>
<script src="<?php echo $this->url->get('js/popper.min.js'); ?>"></script>
<script src="<?php echo $this->url->get('js/bootstrap.min.js'); ?>"></script>
</body>
</html>
